### ISSUE TITLE
Someone hacked unlim-cloud

### ISSUE THREAD

**Issue by ChathuraGH** [inulute/unlim-cloud#7]
I was using telegram years without a problem.
I registered to unlim-cloud with my number.
Now someone took my account. 

I had to **reset** my account to recover it.

### Are your servers hacked?

**Who is responsible?**

**Comment by inulute** [comment]
You are responsible for your own account security. Unlim Cloud's servers are secure, and there has been no breach—almost a million users trust our platform without issues. If you had to reset your account, it means your phone number wasn’t changed and the account was still linked to you.

It’s more likely that you forgot your 2FA password and are now ranting at Unlim Cloud instead of accepting your own mistake.

Stop blaming others and take responsibility. Check your logins and actions before throwing around accusations.

**Comment by ChathuraGH** [comment]
No. I was able to reset because I own the phone number. What happened was someone added another email and was able to get OTP. So they was able to log me out. And they changed account Name and Email. I was only able to recover account because I own my phone number.

**Comment by inulute** [comment]
Oh, I see. However, this has nothing to do with Unlim Cloud's security. As far as I know, new logins can't log out old logins—the session needs to be at least 2-3 days old for that to happen.

Thanks, and have a nice day!

**Comment by ChathuraGH** [comment]
So, It's was like a week after I joined to unlim, that this happened. It was no problem years. One week after I added unlim, this happened. It's obvious, unlim is the leak point. I have no proof. But it's obvious.

**Comment by inulute** [comment]
Your assumptions are misguided. Just because something happened a week after you joined Unlim doesn't mean this project is responsible. Unlim Cloud has around a million users with no reported issues, and this **unofficial project** is **not associated with the official Unlim Cloud project in any way.**

If you have concerns about security, you should raise them directly in the **official Unlim Cloud discussion on Telegram.**


Thanks!

**Comment by ChathuraGH** [comment]
Ok. Can you direct me to the official Unlim Cloud discussion on Telegram.

**Comment by inulute** [comment]
https://t.me/unlimclouddev

**Comment by Kratos1013** [comment]
> Ok. Can you direct me to the official Unlim Cloud discussion on Telegram.

As only developer of Unlim Cloud I can guarantee you that Official Unlim Cloud platform can not be hacked. Unlim Cloud is just an alternative client built on top of Telegram API. Unlim Cloud doesn't share or store any user sensitive information. 

I previewed the source code of inulute/unlim-cloud and didn't find any security issue.

For detailed informations please go to https://t.me/unlimclouddev
